"""Concise database table and column comments."""

from __future__ import annotations

from sqlalchemy import MetaData

SCHEMA_COMMENTS: dict[str, tuple[str, dict[str, str]]] = {
    "users": (
        "系统用户账户。",
        {
            "id": "用户ID。",
            "username": "登录用户名。",
            "password_hash": "密码哈希。",
            "role": "系统角色。",
            "is_active": "账户是否启用。",
            "is_superadmin": "是否为环境配置的超级管理员。",
            "nickname": "用户昵称。",
            "avatar_path": "头像相对路径。",
            "created_at": "创建时间。",
            "updated_at": "更新时间。",
        },
    ),
    "user_sessions": (
        "用户登录会话。",
        {
            "id": "会话ID。",
            "user_id": "用户ID。",
            "device_id": "客户端设备ID。",
            "token_id": "令牌ID。",
            "ip_address": "登录IP地址。",
            "user_agent": "客户端标识。",
            "expires_at": "过期时间。",
            "revoked_at": "撤销时间。",
            "created_at": "创建时间。",
            "updated_at": "更新时间。",
        },
    ),
    "project_registry": (
        "项目身份与所有权。",
        {
            "id": "项目ID。",
            "name": "项目规范名称。",
            "storage_key": "项目文件存储键。",
            "owner_id": "项目所有者用户ID。",
            "created_at": "创建时间。",
            "updated_at": "更新时间。",
        },
    ),
    "project_members": (
        "项目协作者关系。",
        {
            "project_id": "项目ID。",
            "user_id": "协作者用户ID。",
            "role": "项目角色。",
            "created_at": "创建时间。",
            "updated_at": "更新时间。",
        },
    ),
    "assets": (
        "公共资产库。",
        {
            "id": "资产ID。",
            "type": "资产类型。",
            "name": "资产名称。",
            "description": "资产描述。",
            "voice_style": "声音风格。",
            "image_path": "图片相对路径。",
            "audio_path": "音频相对路径。",
            "source_project": "来源项目名称快照。",
            "owner_user_id": "资产上传用户ID。",
            "created_at": "创建时间。",
            "updated_at": "更新时间。",
        },
    ),
    "tasks": (
        "异步生成任务。",
        {
            "task_id": "任务ID。",
            "project_id": "项目ID。",
            "project_name": "项目名称快照。",
            "actor_username": "提交用户名快照。",
            "task_type": "任务类型。",
            "media_type": "媒体类型。",
            "resource_id": "资源ID。",
            "resource_type": "资源类型。",
            "script_file": "剧本文件。",
            "payload_json": "任务请求数据。",
            "status": "任务状态。",
            "result_json": "任务结果数据。",
            "error_message": "失败原因。",
            "source": "任务来源。",
            "dependency_task_id": "依赖任务ID。",
            "dependency_group": "依赖任务组。",
            "dependency_index": "依赖任务顺序。",
            "cancelled_by": "取消来源。",
            "provider_id": "供应商ID。",
            "provider_job_id": "供应商任务ID。",
            "provider_endpoint": "供应商协议标识。",
            "submitted_base_url": "提交服务地址。",
            "execution_checkpoint_json": "执行检查点。",
            "queued_at": "入队时间。",
            "started_at": "开始时间。",
            "finished_at": "完成时间。",
            "updated_at": "更新时间。",
            "user_id": "任务提交用户ID。",
        },
    ),
    "api_calls": (
        "模型调用与费用记录。",
        {
            "id": "调用记录ID。",
            "project_id": "项目ID。",
            "project_name": "项目名称快照。",
            "actor_username": "调用用户名快照。",
            "call_type": "调用类型。",
            "model": "模型ID。",
            "prompt": "调用提示词。",
            "resolution": "输出分辨率。",
            "duration_seconds": "输出时长。",
            "aspect_ratio": "输出比例。",
            "generate_audio": "是否生成音轨。",
            "status": "调用状态。",
            "error_message": "失败原因。",
            "output_path": "输出相对路径。",
            "segment_id": "片段ID。",
            "started_at": "开始时间。",
            "finished_at": "完成时间。",
            "duration_ms": "调用耗时。",
            "retry_count": "重试次数。",
            "cost_amount": "调用费用。",
            "currency": "费用币种。",
            "provider": "供应商ID。",
            "usage_tokens": "总Token数。",
            "input_tokens": "输入Token数。",
            "output_tokens": "输出Token数。",
            "image_input_tokens": "图片输入Token数。",
            "image_output_tokens": "图片输出Token数。",
            "text_input_tokens": "文本输入Token数。",
            "text_output_tokens": "文本输出Token数。",
            "created_at": "创建时间。",
            "updated_at": "更新时间。",
            "user_id": "调用用户ID。",
        },
    ),
    "agent_sessions": (
        "项目智能体会话。",
        {
            "id": "会话ID。",
            "sdk_session_id": "SDK会话ID。",
            "project_id": "项目ID。",
            "project_name": "项目名称快照。",
            "actor_username": "创建用户名快照。",
            "title": "会话标题。",
            "status": "会话状态。",
            "superseded_by": "替代会话ID。",
            "fork_parent_session_id": "父会话ID。",
            "fork_anchor_uuid": "分支锚点消息ID。",
            "created_at": "创建时间。",
            "updated_at": "更新时间。",
            "user_id": "会话创建用户ID。",
        },
    ),
    "agent_session_entries": (
        "SDK会话记录。",
        {
            "project_id": "项目ID。",
            "project_key": "项目存储键。",
            "session_id": "会话ID。",
            "subpath": "会话子路径。",
            "seq": "记录序号。",
            "uuid": "记录UUID。",
            "entry_type": "记录类型。",
            "payload": "记录数据。",
            "mtime_ms": "源修改时间。",
            "created_at": "创建时间。",
            "updated_at": "更新时间。",
            "user_id": "会话创建用户ID。",
        },
    ),
    "agent_session_summaries": (
        "SDK会话摘要。",
        {
            "project_id": "项目ID。",
            "project_key": "项目存储键。",
            "session_id": "会话ID。",
            "mtime_ms": "源修改时间。",
            "data": "摘要数据。",
            "created_at": "创建时间。",
            "updated_at": "更新时间。",
            "user_id": "会话创建用户ID。",
        },
    ),
    "agent_session_event_log": (
        "会话事件日志。",
        {
            "project_id": "项目ID。",
            "session_id": "会话ID。",
            "seq": "事件序号。",
            "entry_type": "事件类型。",
            "payload": "事件数据。",
            "client_key": "客户端幂等键。",
            "created_at": "创建时间。",
            "updated_at": "更新时间。",
            "user_id": "会话创建用户ID。",
        },
    ),
    "agent_session_user_message_links": (
        "会话消息身份映射。",
        {
            "project_id": "项目ID。",
            "session_id": "会话ID。",
            "user_entry_uuid": "用户消息ID。",
            "sdk_entry_uuid": "SDK消息ID。",
            "created_at": "创建时间。",
            "updated_at": "更新时间。",
            "user_id": "会话创建用户ID。",
        },
    ),
    "api_keys": (
        "自动化访问密钥。",
        {
            "id": "密钥记录ID。",
            "user_id": "权限主体用户ID。",
            "name": "密钥名称。",
            "key_hash": "密钥哈希。",
            "key_prefix": "密钥显示前缀。",
            "expires_at": "过期时间。",
            "revoked_at": "撤销时间。",
            "last_used_at": "最近使用时间。",
            "created_at": "创建时间。",
            "updated_at": "更新时间。",
        },
    ),
    "audit_events": (
        "系统审计事件。",
        {
            "id": "审计事件ID。",
            "actor_user_id": "操作用户ID。",
            "actor_username": "操作用户名快照。",
            "action": "操作标识。",
            "resource_type": "资源类型。",
            "resource_id": "资源ID。",
            "project_id": "项目ID。",
            "project_name": "项目名称快照。",
            "details": "操作上下文。",
            "created_at": "发生时间。",
        },
    ),
    "worker_lease": (
        "后台工作进程租约。",
        {"name": "租约名称。", "owner_id": "持有者ID。", "lease_until": "到期时间。", "updated_at": "更新时间。"},
    ),
    "provider_config": (
        "供应商配置。",
        {
            "id": "配置ID。",
            "provider": "供应商ID。",
            "key": "配置键。",
            "value": "配置值。",
            "is_secret": "是否敏感。",
            "updated_at": "更新时间。",
        },
    ),
    "system_setting": (
        "系统设置。",
        {"id": "设置ID。", "key": "设置键。", "value": "设置值。", "updated_at": "更新时间。"},
    ),
    "provider_credential": (
        "供应商凭证。",
        {
            "id": "凭证ID。",
            "provider": "供应商ID。",
            "name": "凭证名称。",
            "api_key": "API密钥。",
            "credentials_path": "凭证文件路径。",
            "base_url": "服务地址。",
            "access_key": "访问密钥。",
            "secret_key": "签名密钥。",
            "is_active": "是否启用。",
            "created_at": "创建时间。",
            "updated_at": "更新时间。",
        },
    ),
    "agent_anthropic_credentials": (
        "用户智能体凭证。",
        {
            "id": "凭证ID。",
            "user_id": "用户ID。",
            "preset_id": "预设ID。",
            "display_name": "显示名称。",
            "base_url": "服务地址。",
            "api_key": "API密钥。",
            "model": "默认模型ID。",
            "haiku_model": "Haiku模型ID。",
            "sonnet_model": "Sonnet模型ID。",
            "opus_model": "Opus模型ID。",
            "subagent_model": "子智能体模型ID。",
            "is_active": "是否启用。",
            "created_at": "创建时间。",
            "updated_at": "更新时间。",
        },
    ),
    "custom_provider": (
        "自定义供应商。",
        {
            "id": "供应商ID。",
            "display_name": "显示名称。",
            "discovery_format": "发现协议。",
            "base_url": "服务地址。",
            "api_key": "API密钥。",
            "image_max_workers": "图片并发上限。",
            "video_max_workers": "视频并发上限。",
            "audio_max_workers": "音频并发上限。",
            "created_at": "创建时间。",
            "updated_at": "更新时间。",
        },
    ),
    "custom_provider_model": (
        "自定义供应商模型。",
        {
            "id": "模型记录ID。",
            "provider_id": "供应商ID。",
            "model_id": "模型ID。",
            "display_name": "显示名称。",
            "endpoint": "端点类型。",
            "is_default": "是否默认。",
            "is_enabled": "是否启用。",
            "price_unit": "计价单位。",
            "price_input": "输入价格。",
            "price_output": "输出价格。",
            "currency": "计价币种。",
            "supported_durations": "支持时长。",
            "resolution": "默认分辨率。",
            "capability_overrides": "能力覆盖。",
            "created_at": "创建时间。",
            "updated_at": "更新时间。",
        },
    ),
}


def apply_schema_comments(metadata: MetaData) -> None:
    """Attach declared comments to tables already registered in metadata."""

    for table_name, (table_comment, column_comments) in SCHEMA_COMMENTS.items():
        table = metadata.tables.get(table_name)
        if table is None:
            continue
        table.comment = table_comment
        for column_name, comment in column_comments.items():
            if column_name in table.c:
                table.c[column_name].comment = comment
